//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketMatik.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KasaGunlukToplam
    {
        public long KasaToplamID { get; set; }
        public string Tarih { get; set; }
        public string Ciro { get; set; }
        public string Kar { get; set; }
        public string Giderler { get; set; }
    }
}
