//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketMatik.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KasaAylik
    {
        public long KasaAylikID { get; set; }
        public string Tarih { get; set; }
        public string KasaAylikCiro { get; set; }
        public string KasaAylikKar { get; set; }
        public string KasaAylikGider { get; set; }
    }
}
