//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketMatik.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public long ID { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriBakiyesi { get; set; }
    }
}
